### ISSUE TITLE
Font in screen shots?

### ISSUE THREAD

**Issue by Vistaus** [myklhenn/my-fish-prompt#1]
Nice looking shell, I love it! But what terminal font did you use in the screen shots?

**Comment by myklhenn** [comment]
Thank you! The font I used is [Terminus](http://terminus-font.sourceforge.net/) (updated TTF version available [here](https://files.ax86.net/terminus-ttf/)). It is one of my favorite terminal fonts!

**Comment by Vistaus** [comment]
Thanks! :)
